@startuml
start
:Адміністратор входить у систему;
:Відкриває панель адміністрування;
:Обирає операцію;
if (Є права доступу?) then (так)
  :Виконується дія через API;
  :Показується результат;
else (ні)
  :Відображається відмова у доступі;
endif
stop
@enduml
