apiVersion: v1
kind: Service
metadata:
  name: nra-api-service
  namespace: natural-resources
spec:
  selector:
    app: nra-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
