apiVersion: v1
kind: Service
metadata:
  name: natural-resources-api
spec:
  selector:
    app: natural-resources-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
