@startuml
start
:Відкрити форму спостереження;
:Ввести тип ресурсу, територію, показник, значення;
if (Дані коректні?) then (так)
  :Надіслати JSON-запит на сервер;
  :Отримати відповідь API;
  :Оновити список спостережень;
else (ні)
  :Показати повідомлення про помилку;
endif
stop
@enduml
