apiVersion: apps/v1
kind: Deployment
metadata:
  name: natural-resources-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: natural-resources-api
  template:
    metadata:
      labels:
        app: natural-resources-api
    spec:
      containers:
        - name: api
          image: natural-resources-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
