apiVersion: v1
kind: Service
metadata:
  name: natural-resources-api-service
spec:
  type: LoadBalancer
  selector:
    app: natural-resources-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
